const data =  [{value: '烏頭(Aconitum Napellus)'},{value: '醫生和牙醫的恐懼'},{value: '急性猛烈高燒'},{value: '流感和傷風'},{value: '絞痛驅使彎腰'},
    {value: '荷蘭芹(Aethusa Cyuapium)'},{value: '牛奶過敏'},{value: '霍亂疾病兒童'},{value: '小朋友嘔奶'},{value: '飲牛奶令腹瀉加劇'},
    {value: '洋蔥(Allium  Cepa)'},{value: '濕凍環境引發傷風'},{value: '鼻腔排出物辛辣性'},{value: '流鼻水導致鼻腔及上唇擦損'},{value: '發癢引起咳嗽為了減輕喉部不適'},
    {value: '酒石酸銻(Antimonium Tartaricum)'},{value: '好多痰'},{value: '浸住喉嚨'},{value: '痰吐唔出'},{value: '痰聲重但出痰少'},
    {value: '蜜蜂(Apis Mellifica)'},{value: '食物敏感'},{value: '過敏性臉'},{value: '特別眼蓋腫'},{value: '腦膜災(腦積水)小朋友'},{value: '因過敏導致休克'},
    {value: '山金車(Arnica Montana)'},{value: '微絲血管爆裂'},{value: '各種形式傷害和創傷'},{value: '流感時疼痛的肌肉'},{value: '乳房被撞形成硬塊導致乳癌'},{value: '防止傷口含膿及潰爛'},
    {value: '砷(Arsenicum Album)'},{value: '情緒焦慮'},{value: '灼熱痛(躁動,不斷地轉換地點)'},{value: '舒緩癌症恐懼'},{value: '間歇性發燒'},{value: '皮膚症狀與哮喘或內部毛病交替'},
    {value: '野靛草(Baptisia Tinctoria)'},{value: '肚子裡下垂感覺'},{value: '全身辛苦感覺'},{value: '睡眼惺忪的眼睛'},{value: '全身酸痛'},{value: '深度虛脫'},
    {value: '顛茄(Belladonma)'},{value: '兒童的療劑'},{value: '中耳炎'},{value: '充血性頭痛'},{value: '突眼性甲狀腺腫'},{value: '狂犬病'},
    {value: '英國雛菊(Bellis Perennis)'},{value: '深層組織受傷'},{value: '靜脈淤滯'},
    {value: '白瀉根(Bryonia Alba)'},{value: '尖銳的痛'},{value: '頭痛欲裂'},{value: '胸肌膜痛'},
    {value: '碳酸鈣(Calcarea Carbonical)'},{value: '肥肥白白'},{value: '肌肉鬆弛'},{value: '佝僂病'},{value: '渴食雞蛋'},
    {value: '金盞花(Calendula Officinalis)'},{value: '物理因素'},{value: '任何擦傷'},{value: '靜脈曲張腫脹'},{value: '傷口出血'},{value: '傷口部位消毒'},{value: '手術後'},{value: '傷口凍'},
    {value: '班蝥(Cantharis Vesicatoria)'},{value: '膀胱炎'},{value: '膀胱感染'},{value: '性器官發炎'},{value: '尿道灼熱'},{value: '燒傷和燙傷'},
    {value: '木炭(Carbo Vegetabilis)'},{value: '窒息'},{value: '缺乏空氣'},{value: '非常虛弱'},{value: '壓迫和呼吸加快'},
    {value: '苛性鈉(Causticum)'},{value: '面部神經麻痺'},{value: '前列腺炎'},{value: '殘年老人'},{value: '肌肉局部癱瘓'},{value: '中風右側'},
    {value: '洋甘菊(Chamomilla)'},{value: '中耳炎'},{value: '耳部劇痛'},{value: '糞便帶酸'},{value: '過度飲用咖啡'},{value: '蒼白(頭出熱汗)'},
    {value: '金雞鈉(China Officinalis)'},{value: '大量經血流'},{value: '旅行者腹瀉'},{value: '好多脹氣'},
    {value: '黑升麻(Cimicifuga Racemosa)'},{value: ''},{value: ''},{value: ''},{value: ''},
    {value: '驅蟲籽(Cina Maritima)'},{value: ''},{value: ''},{value: ''},{value: ''},
    {value: '印度防已(Cocculus Indicus)'},{value: ''},
    {value: '秋水仙(Colchicum Autumnale)'},{value: ''},
    {value: '苦西瓜瓤(Colocynthis)'},{value: ''},
    {value: '毒參(Conium Maculatum)'},{value: ''},
    {value: '銅(Cuprum Metallicum)'},{value: ''},
    {value: '毛地黃素(Digitalis Purpurea)'},{value: ''},
    {value: '歐白英(Dulcamara)'},{value: ''},
    {value: '磷酸鐵(Ferrum Phosphoricum)'},{value: ''},
    {value: '黃素馨(Gelsemium)'},{value: ''},
    {value: '硝酸甘油(Glonoine)'},{value: ''},
    {value: '石墨(Graphites Naturalis)'},{value: ''},
    {value: '硫化鈣(Calcium Sulphide)'},{value: ''},
    {value: '黑茛菪(Hyoscyamus Niger)'},{value: ''},
    {value: '金絲桃(Hypericum perforatum)'},{value: ''},
    {value: '呂宋果(Ignatia Amara)'},{value: ''},
    {value: '吐根(Ipecacuanha)'},{value: ''},
    {value: '杜香(Ledum Palustre)'},{value: ''},
    {value: '石松(Lycopodium)'},{value: ''},
    {value: '溶汞(Mercurius Solublis)'},{value: ''},
    {value: '氯化钠(Natrum muriaticum)'},{value: ''},
    {value: '馬錢子(Nux Vomica)'},{value: ''},
    {value: '磷酸(Phosphoricum Acidum)'},{value: ''},
    {value: '磷(Phosphorus)'},{value: ''},
    {value: '白頭翁(Pulsatilla Nigricums)'},{value: ''},
    {value: '野葛(Rhus toxicodendron)'},{value: ''},
    {value: '芸香(Ruta graveolens)'},{value: ''},
    {value: '墨魚汁(Sepia Succus)'},{value: ''},
    {value: '赤根草(Spigelia Anthelmintia)'},{value: ''},
    {value: '硫磺(Sulphur)'},{value: ''},
    {value: '蕁麻(Urticaria)'},{value: ''},
    {value: '馬栗子(Aesculus Hippocastanum)'},
    {value: '毒蠅傘(Agaricus Muscarius)'},
    {value: '蘆薈(Aloe Socotrina)'},
    {value: '氧化鋁(Aluminum Oxydata)'},
    {value: '馬六甲豆(Anacardium Orientale)'},
    {value: '琉璃繁縷(Anagallis Arvensis)'},
    {value: '硫化銻(Antimonium Crudum)'},
    {value: '硝酸銀(Argentum Nitricum)'},
    {value: '蕪菁(Arum Triphyllum)'},
    {value: '蘆葦(Arundo Mauritanica)'},
    {value: '阿魏膠(Asafoetida)'},
    {value: '黃花馬利筋(Asclepias Tuberosa)'},
    {value: '黃金(Aurum Metallicum)'},
    {value: '碳酸鋇(Baryta Carbonica)'},
    {value: '苯甲酸(Benzoicum Acidum)'},
    {value: '伏牛花(Berberis Vulgaris)'},
    {value: '硼砂(Borax Veneta)'},
    {value: '馬勃菌(Bovista Lycoperdon)'},
    {value: '大花仙人掌(Cactus Grandiflorus)'},
    {value: '氟酸鈣(Calcarea Fluorica)'},
    {value: '磷酸鈣(Calcarea Phosphorica)'},
    {value: '硫酸鈣(Calcarea Sulphurica)'},
    {value: '印度大麻(Cannabis Indica)'},
    {value: '辣椒(Capsicum Annuum)'},
    {value: '聖馬利亞薊草(Carduus Marianus)'},
    {value: '白屈菜(Chelidonium Majus)'},
    {value: '毒芹(Cicuta Virosa)'},
    {value: '岩薔薇黃花(Cistus Canadensis)'},
    {value: '古柯葉(Coca Erythroxylon)'},
    {value: '咖啡(Coffea Cruda)'},
    {value: '毛氈苔(Drosera Rotundifolia)'},
    {value: '藍桉樹(Eucalyptus Globulus)'},
    {value: '蘭草(Eupatorium Perfoliatum)'},
    {value: '小米草(Euphrasia Officinalis)'},
    {value: '重鉻酸鉀(Kali Bichromicum)'},
    {value: '南美蛇毒(Lachesis Muta)'},
    {value: '磷酸鎂(Magnesia Phosphorica)'},
    {value: '蝕汞(Mercurius Corrosivus)'},
    {value: '洋商陸(Phytolacca Decandra)'},
    {value: '足葉草(Podophyllum Peltatum)'},
    {value: '熱源(Pyrogenium)'},
    {value: '水楊酸(Salicylicum acidum)'},
    {value: '矽土(Silica Terra)'},
    {value: '海棉(Spongia Tosta)'},
    {value: '飛燕草(Staphysagria Delphinium)'},
    {value: '接骨草(Symphytum Officinale)'},
    {value: '煙草 (Tabacum Fumus)'},
    {value: '側柏 (Thuja Occidentalis)'},
    {value: '結核素 (Tuberculinum Bovinum)'},
    {value: '白藜蘆 (Veratrum Album)'},

   // {text: 'suggestion1', anotherProperty: 'value'},

    ];


export default data;





